### ISSUE TITLE
Run the catdoc in the linux

### ISSUE THREAD

**Issue by mendickxiao** [OWASP/Serverless-Goat#12]
I test the catdoc in the linux, it is failed.
[ec2-user@lin-0aff6deb convert]$ curl --silent -L https://www.puresec.io/hubfs/document.doc | /lib64/ld-linux-x86-64.so.2 ./bin/catdoc -d "/home/ec2-user/serverless-python/src/api/convert/bin/charsets" -
Cannot load charset cp1251 - file not found

**Comment by 0xh0b0** [comment]
Please run with modified `HOME` environment variable:
```
HOME=/home/ec2-user/serverless-python/src/api/convert curl --silent -L https://www.puresec.io/hubfs/document.doc | /lib64/ld-linux-x86-64.so.2 ./bin/catdoc
```

**Comment by mendickxiao** [comment]
It is hard to use the catdoc, I use the cat to replace it for my testing.
