### ISSUE TITLE
covert function failed

### ISSUE THREAD

**Issue by mendickxiao** [OWASP/Serverless-Goat#9]
Build the owasp-serverless-goat by the AWS Serverless Application Repository https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:761130837472:applications~serverless-goat, but when I want to do the covert, it is failed. I meet this issue before. So I get the code directly from master branch, I still found this issue again.

https://8bxg013urf.execute-api.us-east-1.amazonaws.com/api/convert?document_url=https%3A%2F%2Ffoobar%3B+cat+%2Fvar%2Ftask%2Findex.js+%23

{"message":"Forbidden"}

**Comment by 0xh0b0** [comment]
Please try to completely remove `serverlessrepo-serverless-goat` CloudFormation stack from your account and deploy it again from application repository.

**Comment by mendickxiao** [comment]
I deploy it again and I found the request is not sent to Lambda, it is blocked by somewhere else, but I don't know the details.

https://unfnqzim4m.execute-api.us-east-1.amazonaws.com/api/convert?document_url=https%3A%2F%2Fwww.puresec.io%2Fhubfs%2Fdocument.doc

I got the error message:
{"message":"Forbidden"}

**Comment by mendickxiao** [comment]
Get the resource failed.
https://unfnqzim4m.execute-api.us-east-1.amazonaws.com/favicon.ico

**Comment by mendickxiao** [comment]
I find the reason, I need to deploy the API manually, please close the ticket.
On the API Gateway dashboard choose Resources, click Actions and choose Deploy API. Before your first deployment the only response you'll get is the {"message":"Forbidden"}.

**Comment by mathangi28** [comment]
@mendickxiao i am getting the same error , can you please guide me
